//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MuaSamTT_nhom4.Module.MuaSamThoiTrang
{

    public partial class CT_PHIEU_NHAP : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fmaCTNH;
        [DevExpress.Xpo.DisplayName(@"Mã CT Phiếu Nhập")]
        public string maCTNH
        {
            get { return fmaCTNH; }
            set { SetPropertyValue<string>(nameof(maCTNH), ref fmaCTNH, value); }
        }
        PHIEU_NHAP_HANG fmaPN;
        [Association(@"CT_PHIEU_NHAPReferencesPHIEU_NHAP_HANG")]
        [DevExpress.Xpo.DisplayName(@"Mã phiếu nhập")]
        public PHIEU_NHAP_HANG maPN
        {
            get { return fmaPN; }
            set { SetPropertyValue<PHIEU_NHAP_HANG>(nameof(maPN), ref fmaPN, value); }
        }
        SAN_PHAM fmaSP;
        [Association(@"CT_PHIEU_NHAPReferencesSAN_PHAM")]
        [DevExpress.Xpo.DisplayName(@"Mấ sản phẩm")]
        public SAN_PHAM maSP
        {
            get { return fmaSP; }
            set { SetPropertyValue<SAN_PHAM>(nameof(maSP), ref fmaSP, value); }
        }
        decimal fGiaNhap;
        [DevExpress.Xpo.DisplayName(@"Giá nhập")]
        public decimal GiaNhap
        {
            get { return fGiaNhap; }
            set { SetPropertyValue<decimal>(nameof(GiaNhap), ref fGiaNhap, value); }
        }
        int fSoLuong;
        [DevExpress.Xpo.DisplayName(@"Số lượng")]
        public int SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<int>(nameof(SoLuong), ref fSoLuong, value); }
        }
        decimal fTienChiecKhau;
        [DevExpress.Xpo.DisplayName(@"tiền chiếc khấu")]
        public decimal TienChiecKhau
        {
            get { return fTienChiecKhau; }
            set { SetPropertyValue<decimal>(nameof(TienChiecKhau), ref fTienChiecKhau, value); }
        }
        decimal fThanhTien;
        [DevExpress.Xpo.DisplayName(@"Thành tiền")]
        public decimal ThanhTien
        {
            get { return fThanhTien; }
            set { SetPropertyValue<decimal>(nameof(ThanhTien), ref fThanhTien, value); }
        }
    }

}
