 //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace MuaSamTT_nhom4.Module.MuaSamThoiTrang
{
    [DefaultClassOptions]
    public partial class DANH_GIA : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fMaDG;
        [DevExpress.Xpo.DisplayName(@"Mã Đánh Giá")]
        public string MaDG
        {
            get { return fMaDG; }
            set { SetPropertyValue<string>(nameof(MaDG), ref fMaDG, value); }
        }
        string fMoTa;
        [DevExpress.Xpo.DisplayName(@"Mô Tả")]
        public string MoTa
        {
            get { return fMoTa; }
            set { SetPropertyValue<string>(nameof(MoTa), ref fMoTa, value); }
        }
        KHACH_HANG fMaKH;
        [Association(@"DANH_GIAReferencesKHACH_HANG")]
        [DevExpress.Xpo.DisplayName(@"Mã khách Hàng")]
        public KHACH_HANG MaKH
        {
            get { return fMaKH; }
            set { SetPropertyValue<KHACH_HANG>(nameof(MaKH), ref fMaKH, value); }
        }
    }

}
