//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
using DevExpress.ExpressApp;
namespace MuaSamTT_nhom4.Module.MuaSamThoiTrang
{
    [DefaultClassOptions]
    public partial class DAT_HANG : DevExpress.Persistent.BaseImpl.BaseObject
    {
        protected override void OnDeleting()
        {

            if (CT_DAT_HANGs.Count > 0)
            {
                throw new UserFriendlyException("Không thể xoá Đơn Đặt này vì nó liên quan đến các CT_Đơn Đặt Trong Hệ Thống!");
            }
            base.OnDeleting();
        }
        DAT_HANG fMaDH;
        [DevExpress.Xpo.DisplayName(@"Mã Đặt Hàng")]
        public DAT_HANG MaDH
        {
            get { return fMaDH; }
            set { SetPropertyValue<DAT_HANG>(nameof(MaDH), ref fMaDH, value); }
        }
        KHACH_HANG fMaKH;
        [Association(@"DAT_HANGReferencesKHACH_HANG")]
        [DevExpress.Xpo.DisplayName(@"Mã Khách Hàng")]
        public KHACH_HANG MaKH
        {
            get { return fMaKH; }
            set { SetPropertyValue<KHACH_HANG>(nameof(MaKH), ref fMaKH, value); }
        }
        DateTime fNgayDH;
        [DevExpress.Xpo.DisplayName(@"Ngày Đặt Hàng")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm")]
        public DateTime NgayDH
        {
            get { return fNgayDH; }
            set { SetPropertyValue<DateTime>(nameof(NgayDH), ref fNgayDH, value); }
        }
        string fTrangThai;
        [DevExpress.Xpo.DisplayName(@"Trạng Thái")]
        public string TrangThai
        {
            get { return fTrangThai; }
            set { SetPropertyValue<string>(nameof(TrangThai), ref fTrangThai, value); }
        }
        THONG_KE fMaTK;
        [Association(@"DAT_HANGReferencesTHONG_KE")]
        [DevExpress.Xpo.DisplayName(@"Mã Thống Kê")]
        public THONG_KE MaTK
        {
            get { return fMaTK; }
            set { SetPropertyValue<THONG_KE>(nameof(MaTK), ref fMaTK, value); }
        }
        [Association(@"CT_DAT_HANGReferencesDAT_HANG"), Aggregated]
        public XPCollection<CT_DAT_HANG> CT_DAT_HANGs { get { return GetCollection<CT_DAT_HANG>(nameof(CT_DAT_HANGs)); } }
    }

}
