//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MuaSamTT_nhom4.Module.MuaSamThoiTrang
{

    public partial class DAT_HANG : DevExpress.Persistent.BaseImpl.BaseObject
    {
        DAT_HANG fMaDH;
        [DevExpress.Xpo.DisplayName(@"Mã Đặt Hàng")]
        public DAT_HANG MaDH
        {
            get { return fMaDH; }
            set { SetPropertyValue<DAT_HANG>(nameof(MaDH), ref fMaDH, value); }
        }
        KHACH_HANG fMaKH;
        [Association(@"DAT_HANGReferencesKHACH_HANG")]
        [DevExpress.Xpo.DisplayName(@"Mã Khách Hàng")]
        public KHACH_HANG MaKH
        {
            get { return fMaKH; }
            set { SetPropertyValue<KHACH_HANG>(nameof(MaKH), ref fMaKH, value); }
        }
        DateTime fNgayDH;
        [DevExpress.Xpo.DisplayName(@"Ngày Đặt Hàng")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm")]
        public DateTime NgayDH
        {
            get { return fNgayDH; }
            set { SetPropertyValue<DateTime>(nameof(NgayDH), ref fNgayDH, value); }
        }
        string fTrangThai;
        [DevExpress.Xpo.DisplayName(@"Trạng Thái")]
        public string TrangThai
        {
            get { return fTrangThai; }
            set { SetPropertyValue<string>(nameof(TrangThai), ref fTrangThai, value); }
        }
        decimal fPhíGiaoHang;
        [DevExpress.Xpo.DisplayName(@"Phí giao hàng")]
        public decimal PhíGiaoHang
        {
            get { return fPhíGiaoHang; }
            set { SetPropertyValue<decimal>(nameof(PhíGiaoHang), ref fPhíGiaoHang, value); }
        }
        DateTime fNgayGiaoDuKien;
        public DateTime NgayGiaoDuKien
        {
            get { return fNgayGiaoDuKien; }
            set { SetPropertyValue<DateTime>(nameof(NgayGiaoDuKien), ref fNgayGiaoDuKien, value); }
        }
        DateTime fNgayGiaoThucTe;
        public DateTime NgayGiaoThucTe
        {
            get { return fNgayGiaoThucTe; }
            set { SetPropertyValue<DateTime>(nameof(NgayGiaoThucTe), ref fNgayGiaoThucTe, value); }
        }
        decimal fTongTien;
        public decimal TongTien
        {
            get { return fTongTien; }
            set { SetPropertyValue<decimal>(nameof(TongTien), ref fTongTien, value); }
        }
        NGUOI_GIAO_HANG fMaNGH;
        [Association(@"DAT_HANGReferencesNGUOI_GIAO_HANG")]
        public NGUOI_GIAO_HANG MaNGH
        {
            get { return fMaNGH; }
            set { SetPropertyValue<NGUOI_GIAO_HANG>(nameof(MaNGH), ref fMaNGH, value); }
        }
        [Association(@"CT_DAT_HANGReferencesDAT_HANG"), Aggregated]
        public XPCollection<CT_DAT_HANG> CT_DAT_HANGs { get { return GetCollection<CT_DAT_HANG>(nameof(CT_DAT_HANGs)); } }
    }

}
