//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MuaSamTT_nhom4.Module.MuaSamThoiTrang
{

    public partial class HOA_DON : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fMaHD;
        [DevExpress.Xpo.DisplayName(@"Mã Hoá Đơn")]
        public string MaHD
        {
            get { return fMaHD; }
            set { SetPropertyValue<string>(nameof(MaHD), ref fMaHD, value); }
        }
        KHACH_HANG fMaKH;
        [Association(@"HOA_DONReferencesKHACH_HANG")]
        [DevExpress.Xpo.DisplayName(@"Mã Khách Hàng")]
        public KHACH_HANG MaKH
        {
            get { return fMaKH; }
            set { SetPropertyValue<KHACH_HANG>(nameof(MaKH), ref fMaKH, value); }
        }
        DateTime fNgayLapHD;
        [DevExpress.Xpo.DisplayName(@"Ngày Lập Hoá Đơn")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm")]
        public DateTime NgayLapHD
        {
            get { return fNgayLapHD; }
            set { SetPropertyValue<DateTime>(nameof(NgayLapHD), ref fNgayLapHD, value); }
        }
        NHAN_VIEN fMaNV;
        [Association(@"HOA_DONReferencesNHAN_VIEN")]
        [DevExpress.Xpo.DisplayName(@"Mã Nhân Viên")]
        public NHAN_VIEN MaNV
        {
            get { return fMaNV; }
            set { SetPropertyValue<NHAN_VIEN>(nameof(MaNV), ref fMaNV, value); }
        }
        decimal fTongTien;
        [PersistentAlias("CT_DAT_HANGs.Sum(ct => ct.ThanhTien)")]
        [DevExpress.Xpo.DisplayName(@"Tổng Tiền")]
        public decimal TongTien
        {
            get
            {
                return Convert.ToDecimal(EvaluateAlias(nameof(TongTien)));
            }

            set { SetPropertyValue<decimal>(nameof(TongTien), ref fTongTien, value); }
        }
        [Association(@"CT_DAT_HANGReferencesHOA_DON"), Aggregated]
        public XPCollection<CT_DAT_HANG> CT_DAT_HANGs { get { return GetCollection<CT_DAT_HANG>(nameof(CT_DAT_HANGs)); } }
    }

}
