//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
using DevExpress.ExpressApp;
using DevExpress.Persistent.Validation;
namespace MuaSamTT_nhom4.Module.MuaSamThoiTrang
{
    [DefaultClassOptions]
    public partial class HOA_DON : DevExpress.Persistent.BaseImpl.BaseObject
    {
        protected override void OnDeleting()
        {

            if (CT_DAT_HANGs.Count > 0)
            {
                throw new UserFriendlyException("Không thể xoá Hoá Đơn này vì nó liên quan đến các CT_Đơn Đặt Trong Hệ Thống!");
            }
            base.OnDeleting();
        }
        string fMaHD;
        [DevExpress.Xpo.DisplayName(@"Mã Hoá Đơn")]
        [RuleUniqueValue(DefaultContexts.Save, CustomMessageTemplate = "Mã Hoá Đơn phải là duy nhất.")]
        public string MaHD
        {
            get { return fMaHD; }
            set { SetPropertyValue<string>(nameof(MaHD), ref fMaHD, value); }
        }
        KHACH_HANG fMaKH;
        [Association(@"HOA_DONReferencesKHACH_HANG")]
        [DevExpress.Xpo.DisplayName(@"Mã Khách Hàng")]
        public KHACH_HANG MaKH
        {
            get { return fMaKH; }
            set { SetPropertyValue<KHACH_HANG>(nameof(MaKH), ref fMaKH, value); }
        }
        DateTime fNgayLapHD;
        [DevExpress.Xpo.DisplayName(@"Ngày Lập Hoá Đơn")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm")]
        public DateTime NgayLapHD
        {
            get { return fNgayLapHD; }
            set { SetPropertyValue<DateTime>(nameof(NgayLapHD), ref fNgayLapHD, value); }
        }
        NHAN_VIEN fMaNV;
        [Association(@"HOA_DONReferencesNHAN_VIEN")]
        [DevExpress.Xpo.DisplayName(@"Mã Nhân Viên")]
        public NHAN_VIEN MaNV
        {
            get { return fMaNV; }
            set { SetPropertyValue<NHAN_VIEN>(nameof(MaNV), ref fMaNV, value); }
        }
        decimal fTongTien;
        [DevExpress.Xpo.DisplayName(@"Tổng Tiền")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
        DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal TongTien
        {
            get {
                decimal Sum = 0;
                foreach (CT_DAT_HANG item in CT_DAT_HANGs)
                {
                    Sum += item.ThanhTien;
                }
                
                return Sum; 
            
            }
            set { SetPropertyValue<decimal>(nameof(TongTien), ref fTongTien, value); }
        }
        [Association(@"CT_DAT_HANGReferencesHOA_DON"), Aggregated]
        public XPCollection<CT_DAT_HANG> CT_DAT_HANGs { get { return GetCollection<CT_DAT_HANG>(nameof(CT_DAT_HANGs)); } }
    }

}
