//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.ExpressApp;
namespace MuaSamTT_nhom4.Module.MuaSamThoiTrang
{
   
    [DefaultProperty("TenKH")]
    public partial class KHACH_HANG : DevExpress.Persistent.BaseImpl.BaseObject
    {
        protected override void OnDeleting()
        {

            if (DANH_GIAs.Count > 0)
            {
                throw new UserFriendlyException("Không thể xoá Khách Hàng  này vì nó liên quan đến các Đánh Giá Trong Hệ Thống!");
            }
            if (HOA_DONs.Count > 0)
            {
                throw new UserFriendlyException("Không thể xoá Khách Hàng này vì nó liên quan đến các Hoá Đơn Đặt Trong Hệ Thống!");
            }
            if (DAT_HANGs.Count > 0)
            {
                throw new UserFriendlyException("Không thể xoá Khách Hàng này vì nó liên quan đến các Đặt Hàng Đặt Trong Hệ Thống!");
            }
            base.OnDeleting();
        }
        string fMaKH;
        [DevExpress.Xpo.DisplayName(@"Mã Khách Hàng")]
        public string MaKH
        {
            get { return fMaKH; }
            set { SetPropertyValue<string>(nameof(MaKH), ref fMaKH, value); }
        }
        string fTenKH;
        [DevExpress.Xpo.DisplayName(@"Họ Tên Khách Hàng")]
        public string TenKH
        {
            get { return fTenKH; }
            set { SetPropertyValue<string>(nameof(TenKH), ref fTenKH, value); }
        }
        string fSoDT;

        [DevExpress.Xpo.DisplayName(@"Số Điện Thoại")]
        public string SoDT
        {
            get { return fSoDT; }
            set { SetPropertyValue<string>(nameof(SoDT), ref fSoDT, value); }
        }
        string fDiaChi;
        [DevExpress.Xpo.DisplayName(@"Địa Chỉ")]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        string fGhiChu;
        [DevExpress.Xpo.DisplayName(@"Ghi Chú")]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>(nameof(GhiChu), ref fGhiChu, value); }
        }
        [Association(@"DANH_GIAReferencesKHACH_HANG"), Aggregated]
        public XPCollection<DANH_GIA> DANH_GIAs { get { return GetCollection<DANH_GIA>(nameof(DANH_GIAs)); } }
        [Association(@"HOA_DONReferencesKHACH_HANG"), Aggregated]
        public XPCollection<HOA_DON> HOA_DONs { get { return GetCollection<HOA_DON>(nameof(HOA_DONs)); } }
        [Association(@"DAT_HANGReferencesKHACH_HANG"), Aggregated]
        public XPCollection<DAT_HANG> DAT_HANGs { get { return GetCollection<DAT_HANG>(nameof(DAT_HANGs)); } }
    }

}
