//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MuaSamTT_nhom4.Module.MuaSamThoiTrang
{

    [DefaultProperty("TenKH")]
    public partial class KHACH_HANG : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fMaKH;
        [DevExpress.Xpo.DisplayName(@"Mã Khách Hàng")]
        public string MaKH
        {
            get { return fMaKH; }
            set { SetPropertyValue<string>(nameof(MaKH), ref fMaKH, value); }
        }
        string fTenKH;
        [DevExpress.Xpo.DisplayName(@"Tên Khách hàng")]
        public string TenKH
        {
            get { return fTenKH; }
            set { SetPropertyValue<string>(nameof(TenKH), ref fTenKH, value); }
        }
        string fSoDT;
        [DevExpress.Xpo.DisplayName(@"Số điện thoại")]
        public string SoDT
        {
            get { return fSoDT; }
            set { SetPropertyValue<string>(nameof(SoDT), ref fSoDT, value); }
        }
        string fDiaChi;
        [DevExpress.Xpo.DisplayName(@"Địa chỉ")]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        string fGhiChu;
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>(nameof(GhiChu), ref fGhiChu, value); }
        }
        [Association(@"DANH_GIAReferencesKHACH_HANG"), Aggregated]
        public XPCollection<DANH_GIA> DANH_GIAs { get { return GetCollection<DANH_GIA>(nameof(DANH_GIAs)); } }
        [Association(@"HOA_DONReferencesKHACH_HANG"), Aggregated]
        public XPCollection<HOA_DON> HOA_DONs { get { return GetCollection<HOA_DON>(nameof(HOA_DONs)); } }
        [Association(@"DAT_HANGReferencesKHACH_HANG"), Aggregated]
        public XPCollection<DAT_HANG> DAT_HANGs { get { return GetCollection<DAT_HANG>(nameof(DAT_HANGs)); } }
    }

}
