//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MuaSamTT_nhom4.Module.MuaSamThoiTrang
{

    [
DefaultProperty("tenNCC")]
    public partial class NHA_CUNG_CAP : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fmaNCC;
        [DevExpress.Xpo.DisplayName(@"Mã nhà cung cấp")]
        public string maNCC
        {
            get { return fmaNCC; }
            set { SetPropertyValue<string>(nameof(maNCC), ref fmaNCC, value); }
        }
        string ftenNCC;
        [DevExpress.Xpo.DisplayName(@"Tên Nhà Cung Cấp")]
        public string tenNCC
        {
            get { return ftenNCC; }
            set { SetPropertyValue<string>(nameof(tenNCC), ref ftenNCC, value); }
        }
        string fmaSoThue;
        [DevExpress.Xpo.DisplayName(@"Mã số thuế")]
        public string maSoThue
        {
            get { return fmaSoThue; }
            set { SetPropertyValue<string>(nameof(maSoThue), ref fmaSoThue, value); }
        }
        string fsoDienThoai;
        [DevExpress.Xpo.DisplayName(@"Số điện thoại")]
        public string soDienThoai
        {
            get { return fsoDienThoai; }
            set { SetPropertyValue<string>(nameof(soDienThoai), ref fsoDienThoai, value); }
        }
        string femail;
        [DevExpress.Xpo.DisplayName(@"Email")]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        string fdiaChi;
        [DevExpress.Xpo.DisplayName(@"Địa chỉ")]
        public string diaChi
        {
            get { return fdiaChi; }
            set { SetPropertyValue<string>(nameof(diaChi), ref fdiaChi, value); }
        }
        [Association(@"PHIEU_NHAP_HANGReferencesNHA_CUNG_CAP")]
        public XPCollection<PHIEU_NHAP_HANG> PHIEU_NHAP_HANGs { get { return GetCollection<PHIEU_NHAP_HANG>(nameof(PHIEU_NHAP_HANGs)); } }
    }

}
