//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
using DevExpress.ExpressApp;
using DevExpress.Persistent.Validation;
namespace MuaSamTT_nhom4.Module.MuaSamThoiTrang
{
    [DefaultClassOptions]
    [DefaultProperty("TenNV")]
    public partial class NHAN_VIEN : DevExpress.Persistent.BaseImpl.BaseObject
    {
        protected override void OnDeleting()
        {

            if (HOA_DONs.Count > 0)
            {
                throw new UserFriendlyException("Không thể xoá Nhân Viên này vì nó liên quan đến các Hoá Đơn Trong Hệ Thống!");
            }
            if (THONG_KEs.Count > 0)
            {
                throw new UserFriendlyException("Không thể xoá Nhân Viên này vì nó liên quan đến các Thống Kê Đặt Trong Hệ Thống!");
            }
           
            base.OnDeleting();
        }
        string fMaNV;
        [DevExpress.Xpo.DisplayName(@"Mã Nhân Viên")]
        [RuleUniqueValue(DefaultContexts.Save, CustomMessageTemplate = "Mã Nhân Viên phải là duy nhất.")]
        public string MaNV
        {
            get { return fMaNV; }
            set { SetPropertyValue<string>(nameof(MaNV), ref fMaNV, value); }
        }
        string fTaiKhoan;
        [DevExpress.Xpo.DisplayName(@"Tài Khoản")]
        public string TaiKhoan
        {
            get { return fTaiKhoan; }
            set { SetPropertyValue<string>(nameof(TaiKhoan), ref fTaiKhoan, value); }
        }
        string fTenNV;
        [DevExpress.Xpo.DisplayName(@"Tên Nhân Viên")]
        public string TenNV
        {
            get { return fTenNV; }
            set { SetPropertyValue<string>(nameof(TenNV), ref fTenNV, value); }
        }
        string fDiaChi;
        [DevExpress.Xpo.DisplayName(@"Địa Chỉ")]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        string fDienThoai;
        [DevExpress.Xpo.DisplayName(@"Điện Thoại")]
        public string DienThoai
        {
            get { return fDienThoai; }
            set { SetPropertyValue<string>(nameof(DienThoai), ref fDienThoai, value); }
        }
        string fGhiChu;
        [DevExpress.Xpo.DisplayName(@"Ghi Chú")]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>(nameof(GhiChu), ref fGhiChu, value); }
        }
        [Association(@"HOA_DONReferencesNHAN_VIEN"), Aggregated]
        public XPCollection<HOA_DON> HOA_DONs { get { return GetCollection<HOA_DON>(nameof(HOA_DONs)); } }
        [Association(@"THONG_KEReferencesNHAN_VIEN"), Aggregated]
        public XPCollection<THONG_KE> THONG_KEs { get { return GetCollection<THONG_KE>(nameof(THONG_KEs)); } }
    }

}
