//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MuaSamTT_nhom4.Module.MuaSamThoiTrang
{

    [DefaultProperty("TenNV")]
    public partial class NHAN_VIEN : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fMaNV;
        [DevExpress.Xpo.DisplayName(@"Mã Nhân Viên")]
        public string MaNV
        {
            get { return fMaNV; }
            set { SetPropertyValue<string>(nameof(MaNV), ref fMaNV, value); }
        }
        string fTaiKhoan;
        [DevExpress.Xpo.DisplayName(@"Tài Khoản")]
        public string TaiKhoan
        {
            get { return fTaiKhoan; }
            set { SetPropertyValue<string>(nameof(TaiKhoan), ref fTaiKhoan, value); }
        }
        string fTenNV;
        [DevExpress.Xpo.DisplayName(@"Tên Nhân Viên")]
        public string TenNV
        {
            get { return fTenNV; }
            set { SetPropertyValue<string>(nameof(TenNV), ref fTenNV, value); }
        }
        string fDiaChi;
        [DevExpress.Xpo.DisplayName(@"Địa Chỉ")]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        string fDienThoai;
        [DevExpress.Xpo.DisplayName(@"Điện Thoại")]
        public string DienThoai
        {
            get { return fDienThoai; }
            set { SetPropertyValue<string>(nameof(DienThoai), ref fDienThoai, value); }
        }
        string fGhiChu;
        [DevExpress.Xpo.DisplayName(@"Ghi Chú")]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>(nameof(GhiChu), ref fGhiChu, value); }
        }
        [Association(@"PHIEU_NHAP_HANGReferencesNHAN_VIEN")]
        public XPCollection<PHIEU_NHAP_HANG> PHIEU_NHAP_HANGs { get { return GetCollection<PHIEU_NHAP_HANG>(nameof(PHIEU_NHAP_HANGs)); } }
        [Association(@"HOA_DONReferencesNHAN_VIEN"), Aggregated]
        public XPCollection<HOA_DON> HOA_DONs { get { return GetCollection<HOA_DON>(nameof(HOA_DONs)); } }
    }

}
