//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MuaSamTT_nhom4.Module.MuaSamThoiTrang
{

    public partial class PHIEU_NHAP_HANG : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fMaPN;
        [DevExpress.Xpo.DisplayName(@"Mã Phiếu Nhập")]
        public string MaPN
        {
            get { return fMaPN; }
            set { SetPropertyValue<string>(nameof(MaPN), ref fMaPN, value); }
        }
        NHAN_VIEN fMaNV;
        [Association(@"PHIEU_NHAP_HANGReferencesNHAN_VIEN")]
        [DevExpress.Xpo.DisplayName(@"Mã Nhân Viên")]
        public NHAN_VIEN MaNV
        {
            get { return fMaNV; }
            set { SetPropertyValue<NHAN_VIEN>(nameof(MaNV), ref fMaNV, value); }
        }
        DateTime fNgayNhap;
        [DevExpress.Xpo.DisplayName(@"Ngày Nhập")]
        public DateTime NgayNhap
        {
            get { return fNgayNhap; }
            set { SetPropertyValue<DateTime>(nameof(NgayNhap), ref fNgayNhap, value); }
        }
        decimal fTongTien;
        [DevExpress.Xpo.DisplayName(@"Tổng Tiền")]
        public decimal TongTien
        {
            get { return fTongTien; }
            set { SetPropertyValue<decimal>(nameof(TongTien), ref fTongTien, value); }
        }
        NHA_CUNG_CAP fMaNCC;
        [Association(@"PHIEU_NHAP_HANGReferencesNHA_CUNG_CAP")]
        [DevExpress.Xpo.DisplayName(@"Mã Nhà Cung Cấp")]
        public NHA_CUNG_CAP MaNCC
        {
            get { return fMaNCC; }
            set { SetPropertyValue<NHA_CUNG_CAP>(nameof(MaNCC), ref fMaNCC, value); }
        }
        [Association(@"CT_PHIEU_NHAPReferencesPHIEU_NHAP_HANG")]
        public XPCollection<CT_PHIEU_NHAP> CT_PHIEU_NHAPs { get { return GetCollection<CT_PHIEU_NHAP>(nameof(CT_PHIEU_NHAPs)); } }
    }

}
