//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MuaSamTT_nhom4.Module.MuaSamThoiTrang
{

    [DefaultProperty("TenSP")]
    public partial class SAN_PHAM : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fMaSP;
        public string MaSP
        {
            get { return fMaSP; }
            set { SetPropertyValue<string>(nameof(MaSP), ref fMaSP, value); }
        }
        string fTenSP;
        public string TenSP
        {
            get { return fTenSP; }
            set { SetPropertyValue<string>(nameof(TenSP), ref fTenSP, value); }
        }
        DANH_MUC fMaDM;
        [Association(@"SAN_PHAMReferencesDANH_MUC")]
        public DANH_MUC MaDM
        {
            get { return fMaDM; }
            set { SetPropertyValue<DANH_MUC>(nameof(MaDM), ref fMaDM, value); }
        }
        THUONG_HIEU fMaTH;
        [Association(@"SAN_PHAMReferencesTHUONG_HIEU")]
        public THUONG_HIEU MaTH
        {
            get { return fMaTH; }
            set { SetPropertyValue<THUONG_HIEU>(nameof(MaTH), ref fMaTH, value); }
        }
        decimal fGiaBan;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")
]
        public decimal GiaBan
        {
            get { return fGiaBan; }
            set { SetPropertyValue<decimal>(nameof(GiaBan), ref fGiaBan, value); }
        }
        string fDVT;
        public string DVT
        {
            get { return fDVT; }
            set { SetPropertyValue<string>(nameof(DVT), ref fDVT, value); }
        }
        string fMoTa;
        public string MoTa
        {
            get { return fMoTa; }
            set { SetPropertyValue<string>(nameof(MoTa), ref fMoTa, value); }
        }
        [Association(@"CT_PHIEU_NHAPReferencesSAN_PHAM")]
        public XPCollection<CT_PHIEU_NHAP> CT_PHIEU_NHAPs { get { return GetCollection<CT_PHIEU_NHAP>(nameof(CT_PHIEU_NHAPs)); } }
        [Association(@"CT_DAT_HANGReferencesSAN_PHAM"), Aggregated]
        public XPCollection<CT_DAT_HANG> CT_DAT_HANGs { get { return GetCollection<CT_DAT_HANG>(nameof(CT_DAT_HANGs)); } }
    }

}
