//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.ExpressApp;
using DevExpress.Persistent.Validation;
namespace MuaSamTT_nhom4.Module.MuaSamThoiTrang
{

    [DefaultProperty("TenTH")]
    public partial class THUONG_HIEU : DevExpress.Persistent.BaseImpl.BaseObject
    {
        protected override void OnDeleting()
        {
            if (SAN_PHAMs.Count > 0)
            {
                throw new UserFriendlyException("Không thể xoá Thương Hiệu này vì nó liên quan đến các Sản Phẩm Trong Hệ Thống!");
            }
            base.OnDeleting();
        }
        string fMaTH;
        [DevExpress.Xpo.DisplayName(@"Mã Thương Hiệu")]
        [RuleUniqueValue(DefaultContexts.Save, CustomMessageTemplate = "Mã Thương Hiệu phải là duy nhất.")]

        public string MaTH
        {
            get { return fMaTH; }
            set { SetPropertyValue<string>(nameof(MaTH), ref fMaTH, value); }
        }
        string fTenTH;
        [DevExpress.Xpo.DisplayName(@"Tên Thương Hiệu")]
        public string TenTH
        {
            get { return fTenTH; }
            set { SetPropertyValue<string>(nameof(TenTH), ref fTenTH, value); }
        }
        [Association(@"SAN_PHAMReferencesTHUONG_HIEU"), Aggregated]
        public XPCollection<SAN_PHAM> SAN_PHAMs { get { return GetCollection<SAN_PHAM>(nameof(SAN_PHAMs)); } }
    }

}
